# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apollo_msgs/map_msgs/map_pnc_junction.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_msgs.map_msgs import map_geometry_pb2 as apollo__msgs_dot_map__msgs_dot_map__geometry__pb2
from apollo_msgs.map_msgs import map_id_pb2 as apollo__msgs_dot_map__msgs_dot_map__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+apollo_msgs/map_msgs/map_pnc_junction.proto\x12\x0c\x61pollo.hdmap\x1a\'apollo_msgs/map_msgs/map_geometry.proto\x1a!apollo_msgs/map_msgs/map_id.proto\"\x92\x02\n\x07Passage\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.apollo.hdmap.Id\x12#\n\tsignal_id\x18\x02 \x03(\x0b\x32\x10.apollo.hdmap.Id\x12\"\n\x08yield_id\x18\x03 \x03(\x0b\x32\x10.apollo.hdmap.Id\x12&\n\x0cstop_sign_id\x18\x04 \x03(\x0b\x32\x10.apollo.hdmap.Id\x12!\n\x07lane_id\x18\x05 \x03(\x0b\x32\x10.apollo.hdmap.Id\x12(\n\x04type\x18\x06 \x01(\x0e\x32\x1a.apollo.hdmap.Passage.Type\"+\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x45NTRANCE\x10\x01\x12\x08\n\x04\x45XIT\x10\x02\"T\n\x0cPassageGroup\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.apollo.hdmap.Id\x12&\n\x07passage\x18\x02 \x03(\x0b\x32\x15.apollo.hdmap.Passage\"\xac\x01\n\x0bPNCJunction\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.apollo.hdmap.Id\x12&\n\x07polygon\x18\x02 \x01(\x0b\x32\x15.apollo.hdmap.Polygon\x12$\n\noverlap_id\x18\x03 \x03(\x0b\x32\x10.apollo.hdmap.Id\x12\x31\n\rpassage_group\x18\x04 \x03(\x0b\x32\x1a.apollo.hdmap.PassageGroup')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apollo_msgs.map_msgs.map_pnc_junction_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PASSAGE._serialized_start=138
  _PASSAGE._serialized_end=412
  _PASSAGE_TYPE._serialized_start=369
  _PASSAGE_TYPE._serialized_end=412
  _PASSAGEGROUP._serialized_start=414
  _PASSAGEGROUP._serialized_end=498
  _PNCJUNCTION._serialized_start=501
  _PNCJUNCTION._serialized_end=673
# @@protoc_insertion_point(module_scope)
