# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apollo_msgs/map_msgs/map_geometry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_msgs.basic_msgs import geometry_pb2 as apollo__msgs_dot_basic__msgs_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'apollo_msgs/map_msgs/map_geometry.proto\x12\x0c\x61pollo.hdmap\x1a%apollo_msgs/basic_msgs/geometry.proto\"1\n\x07Polygon\x12&\n\x05point\x18\x01 \x03(\x0b\x32\x17.apollo.common.PointENU\"5\n\x0bLineSegment\x12&\n\x05point\x18\x01 \x03(\x0b\x32\x17.apollo.common.PointENU\"\xac\x01\n\x0c\x43urveSegment\x12\x31\n\x0cline_segment\x18\x01 \x01(\x0b\x32\x19.apollo.hdmap.LineSegmentH\x00\x12\t\n\x01s\x18\x06 \x01(\x01\x12/\n\x0estart_position\x18\x07 \x01(\x0b\x32\x17.apollo.common.PointENU\x12\x0f\n\x07heading\x18\x08 \x01(\x01\x12\x0e\n\x06length\x18\t \x01(\x01\x42\x0c\n\ncurve_type\"4\n\x05\x43urve\x12+\n\x07segment\x18\x01 \x03(\x0b\x32\x1a.apollo.hdmap.CurveSegment')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apollo_msgs.map_msgs.map_geometry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_POLYGON']._serialized_start=96
  _globals['_POLYGON']._serialized_end=145
  _globals['_LINESEGMENT']._serialized_start=147
  _globals['_LINESEGMENT']._serialized_end=200
  _globals['_CURVESEGMENT']._serialized_start=203
  _globals['_CURVESEGMENT']._serialized_end=375
  _globals['_CURVE']._serialized_start=377
  _globals['_CURVE']._serialized_end=429
# @@protoc_insertion_point(module_scope)
