# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apollo_msgs/map_msgs/map_clear_area.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_msgs.map_msgs import map_geometry_pb2 as apollo__msgs_dot_map__msgs_dot_map__geometry__pb2
from apollo_msgs.map_msgs import map_id_pb2 as apollo__msgs_dot_map__msgs_dot_map__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)apollo_msgs/map_msgs/map_clear_area.proto\x12\x0c\x61pollo.hdmap\x1a\'apollo_msgs/map_msgs/map_geometry.proto\x1a!apollo_msgs/map_msgs/map_id.proto\"w\n\tClearArea\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.apollo.hdmap.Id\x12$\n\noverlap_id\x18\x02 \x03(\x0b\x32\x10.apollo.hdmap.Id\x12&\n\x07polygon\x18\x03 \x01(\x0b\x32\x15.apollo.hdmap.Polygon')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apollo_msgs.map_msgs.map_clear_area_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLEARAREA._serialized_start=135
  _CLEARAREA._serialized_end=254
# @@protoc_insertion_point(module_scope)
