# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apollo_msgs/map_msgs/map_junction.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_msgs.map_msgs import map_geometry_pb2 as apollo__msgs_dot_map__msgs_dot_map__geometry__pb2
from apollo_msgs.map_msgs import map_id_pb2 as apollo__msgs_dot_map__msgs_dot_map__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'apollo_msgs/map_msgs/map_junction.proto\x12\x0c\x61pollo.hdmap\x1a\'apollo_msgs/map_msgs/map_geometry.proto\x1a!apollo_msgs/map_msgs/map_id.proto\"\xff\x01\n\x08Junction\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.apollo.hdmap.Id\x12&\n\x07polygon\x18\x02 \x01(\x0b\x32\x15.apollo.hdmap.Polygon\x12$\n\noverlap_id\x18\x03 \x03(\x0b\x32\x10.apollo.hdmap.Id\x12)\n\x04type\x18\x04 \x01(\x0e\x32\x1b.apollo.hdmap.Junction.Type\"\\\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07IN_ROAD\x10\x01\x12\x0e\n\nCROSS_ROAD\x10\x02\x12\r\n\tFORK_ROAD\x10\x03\x12\r\n\tMAIN_SIDE\x10\x04\x12\x0c\n\x08\x44\x45\x41\x44_END\x10\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apollo_msgs.map_msgs.map_junction_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JUNCTION._serialized_start=134
  _JUNCTION._serialized_end=389
  _JUNCTION_TYPE._serialized_start=297
  _JUNCTION_TYPE._serialized_end=389
# @@protoc_insertion_point(module_scope)
