# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apollo_msgs/routing_msgs/poi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_msgs.routing_msgs import routing_pb2 as apollo__msgs_dot_routing__msgs_dot_routing__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"apollo_msgs/routing_msgs/poi.proto\x12\x0e\x61pollo.routing\x1a&apollo_msgs/routing_msgs/routing.proto\"\x99\x01\n\x08Landmark\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\x08waypoint\x18\x02 \x03(\x0b\x32\x1c.apollo.routing.LaneWaypoint\x12\x1c\n\x10parking_space_id\x18\x03 \x01(\tB\x02\x18\x01\x12\x31\n\x0cparking_info\x18\x04 \x01(\x0b\x32\x1b.apollo.routing.ParkingInfo\"1\n\x03POI\x12*\n\x08landmark\x18\x01 \x03(\x0b\x32\x18.apollo.routing.Landmark')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apollo_msgs.routing_msgs.poi_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LANDMARK.fields_by_name['parking_space_id']._options = None
  _LANDMARK.fields_by_name['parking_space_id']._serialized_options = b'\030\001'
  _globals['_LANDMARK']._serialized_start=95
  _globals['_LANDMARK']._serialized_end=248
  _globals['_POI']._serialized_start=250
  _globals['_POI']._serialized_end=299
# @@protoc_insertion_point(module_scope)
