# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/common_msgs/map_msgs/map_road.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.common_msgs.map_msgs import map_geometry_pb2 as modules_dot_common__msgs_dot_map__msgs_dot_map__geometry__pb2
from modules.common_msgs.map_msgs import map_id_pb2 as modules_dot_common__msgs_dot_map__msgs_dot_map__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+modules/common_msgs/map_msgs/map_road.proto\x12\x0c\x61pollo.hdmap\x1a/modules/common_msgs/map_msgs/map_geometry.proto\x1a)modules/common_msgs/map_msgs/map_id.proto\"\xa9\x01\n\x0c\x42oundaryEdge\x12\"\n\x05\x63urve\x18\x01 \x01(\x0b\x32\x13.apollo.hdmap.Curve\x12-\n\x04type\x18\x02 \x01(\x0e\x32\x1f.apollo.hdmap.BoundaryEdge.Type\"F\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06NORMAL\x10\x01\x12\x11\n\rLEFT_BOUNDARY\x10\x02\x12\x12\n\x0eRIGHT_BOUNDARY\x10\x03\";\n\x0f\x42oundaryPolygon\x12(\n\x04\x65\x64ge\x18\x01 \x03(\x0b\x32\x1a.apollo.hdmap.BoundaryEdge\"q\n\x0cRoadBoundary\x12\x34\n\router_polygon\x18\x01 \x01(\x0b\x32\x1d.apollo.hdmap.BoundaryPolygon\x12+\n\x04hole\x18\x02 \x03(\x0b\x32\x1d.apollo.hdmap.BoundaryPolygon\"d\n\x0fRoadROIBoundary\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.apollo.hdmap.Id\x12\x33\n\x0froad_boundaries\x18\x02 \x03(\x0b\x32\x1a.apollo.hdmap.RoadBoundary\"|\n\x0bRoadSection\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.apollo.hdmap.Id\x12!\n\x07lane_id\x18\x02 \x03(\x0b\x32\x10.apollo.hdmap.Id\x12,\n\x08\x62oundary\x18\x03 \x01(\x0b\x32\x1a.apollo.hdmap.RoadBoundary\"\xd9\x01\n\x04Road\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.apollo.hdmap.Id\x12*\n\x07section\x18\x02 \x03(\x0b\x32\x19.apollo.hdmap.RoadSection\x12%\n\x0bjunction_id\x18\x03 \x01(\x0b\x32\x10.apollo.hdmap.Id\x12%\n\x04type\x18\x04 \x01(\x0e\x32\x17.apollo.hdmap.Road.Type\"9\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07HIGHWAY\x10\x01\x12\r\n\tCITY_ROAD\x10\x02\x12\x08\n\x04PARK\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modules.common_msgs.map_msgs.map_road_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BOUNDARYEDGE']._serialized_start=154
  _globals['_BOUNDARYEDGE']._serialized_end=323
  _globals['_BOUNDARYEDGE_TYPE']._serialized_start=253
  _globals['_BOUNDARYEDGE_TYPE']._serialized_end=323
  _globals['_BOUNDARYPOLYGON']._serialized_start=325
  _globals['_BOUNDARYPOLYGON']._serialized_end=384
  _globals['_ROADBOUNDARY']._serialized_start=386
  _globals['_ROADBOUNDARY']._serialized_end=499
  _globals['_ROADROIBOUNDARY']._serialized_start=501
  _globals['_ROADROIBOUNDARY']._serialized_end=601
  _globals['_ROADSECTION']._serialized_start=603
  _globals['_ROADSECTION']._serialized_end=727
  _globals['_ROAD']._serialized_start=730
  _globals['_ROAD']._serialized_end=947
  _globals['_ROAD_TYPE']._serialized_start=890
  _globals['_ROAD_TYPE']._serialized_end=947
# @@protoc_insertion_point(module_scope)
