[tool.poetry]
name = "sce-trans"
version = "0.1.0"
description = ""
authors = ["Changnam"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
lanelet2 = "^1.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
