[tool.poetry]
name = "sce-trans"
version = "0.1.0"
description = ""
authors = ["Changnam"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
lanelet2 = "^1.2.1"
protobuf = "^4.25.0"
pyproj = "^3.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
