# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apollo_msgs/basic_msgs/drive_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_msgs.basic_msgs import header_pb2 as apollo__msgs_dot_basic__msgs_dot_header__pb2
from apollo_msgs.localization_msgs import pose_pb2 as apollo__msgs_dot_localization__msgs_dot_pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(apollo_msgs/basic_msgs/drive_event.proto\x12\rapollo.common\x1a#apollo_msgs/basic_msgs/header.proto\x1a(apollo_msgs/localization_msgs/pose.proto\"\xf6\x01\n\nDriveEvent\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.apollo.common.Header\x12\r\n\x05\x65vent\x18\x02 \x01(\t\x12+\n\x08location\x18\x03 \x01(\x0b\x32\x19.apollo.localization.Pose\x12,\n\x04type\x18\x04 \x03(\x0e\x32\x1e.apollo.common.DriveEvent.Type\x12\x15\n\ris_reportable\x18\x05 \x01(\x08\"@\n\x04Type\x12\x0c\n\x08\x43RITICAL\x10\x00\x12\x0b\n\x07PROBLEM\x10\x01\x12\x0b\n\x07\x44\x45SIRED\x10\x02\x12\x10\n\x0cOUT_OF_SCOPE\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apollo_msgs.basic_msgs.drive_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DRIVEEVENT']._serialized_start=139
  _globals['_DRIVEEVENT']._serialized_end=385
  _globals['_DRIVEEVENT_TYPE']._serialized_start=321
  _globals['_DRIVEEVENT_TYPE']._serialized_end=385
# @@protoc_insertion_point(module_scope)
