# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/by_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fopenscenario_msgs/by_type.proto\x12\x0copenscenario\"6\n\x06\x42yType\x12,\n\nobjectType\x18\x01 \x02(\x0e\x32\x18.openscenario.ObjectType\"6\n\x0c\x42yObjectType\x12&\n\x04type\x18\x01 \x02(\x0e\x32\x18.openscenario.ObjectType*v\n\nObjectType\x12\x1c\n\x18OBJECTTYPE_MISCELLANEOUS\x10\x00\x12\x19\n\x15OBJECTTYPE_PEDESTRIAN\x10\x01\x12\x16\n\x12OBJECTTYPE_VEHICLE\x10\x02\x12\x17\n\x13OBJECTTYPE_EXTERNAL\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openscenario_msgs.by_type_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJECTTYPE._serialized_start=161
  _OBJECTTYPE._serialized_end=279
  _BYTYPE._serialized_start=49
  _BYTYPE._serialized_end=103
  _BYOBJECTTYPE._serialized_start=105
  _BYOBJECTTYPE._serialized_end=159
# @@protoc_insertion_point(module_scope)
