# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1copenscenario_msgs/file.proto\x12\x0copenscenario\"\x18\n\x04\x46ile\x12\x10\n\x08\x66ilepath\x18\x01 \x02(\t')



_FILE = DESCRIPTOR.message_types_by_name['File']
File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), {
  'DESCRIPTOR' : _FILE,
  '__module__' : 'openscenario_msgs.file_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.File)
  })
_sym_db.RegisterMessage(File)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILE._serialized_start=46
  _FILE._serialized_end=70
# @@protoc_insertion_point(module_scope)
