# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/following_mode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&openscenario_msgs/following_mode.proto\x12\x0copenscenario*E\n\rFollowingMode\x12\x18\n\x14\x46OLLOWINGMODE_FOLLOW\x10\x00\x12\x1a\n\x16\x46OLLOWINGMODE_POSITION\x10\x01')

_FOLLOWINGMODE = DESCRIPTOR.enum_types_by_name['FollowingMode']
FollowingMode = enum_type_wrapper.EnumTypeWrapper(_FOLLOWINGMODE)
FOLLOWINGMODE_FOLLOW = 0
FOLLOWINGMODE_POSITION = 1


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FOLLOWINGMODE._serialized_start=56
  _FOLLOWINGMODE._serialized_end=125
# @@protoc_insertion_point(module_scope)
