# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/orientation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#openscenario_msgs/orientation.proto\x12\x0copenscenario\"\\\n\x0bOrientation\x12\t\n\x01h\x18\x01 \x01(\x01\x12\t\n\x01p\x18\x02 \x01(\x01\x12\t\n\x01r\x18\x03 \x01(\x01\x12,\n\x04type\x18\x04 \x01(\x0e\x32\x1e.openscenario.ReferenceContext*P\n\x10ReferenceContext\x12\x1d\n\x19REFERENCECONTEXT_ABSOLUTE\x10\x00\x12\x1d\n\x19REFERENCECONTEXT_RELATIVE\x10\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openscenario_msgs.orientation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REFERENCECONTEXT._serialized_start=147
  _REFERENCECONTEXT._serialized_end=227
  _ORIENTATION._serialized_start=53
  _ORIENTATION._serialized_end=145
# @@protoc_insertion_point(module_scope)
