# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/parameter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openscenario_msgs import rule_pb2 as openscenario__msgs_dot_rule__pb2
from openscenario_msgs import valueconstraint_group_pb2 as openscenario__msgs_dot_valueconstraint__group__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!openscenario_msgs/parameter.proto\x12\x0copenscenairo\x1a\x1copenscenario_msgs/rule.proto\x1a-openscenario_msgs/valueconstraint_group.proto\"_\n\x13ParameterAssignment\x12\x39\n\rparameter_ref\x18\x01 \x02(\x0b\x32\".openscenairo.ParameterDeclaration\x12\r\n\x05value\x18\x02 \x02(\t\"\x7f\n\x12ParameterCondition\x12\x38\n\x0cparameterRef\x18\x01 \x02(\x0b\x32\".openscenairo.ParameterDeclaration\x12 \n\x04rule\x18\x02 \x02(\x0e\x32\x12.openscenairo.Rule\x12\r\n\x05value\x18\x03 \x02(\t\"\xa7\x01\n\x14ParameterDeclaration\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x33\n\x0eparameter_type\x18\x02 \x02(\x0e\x32\x1b.openscenairo.ParameterType\x12\r\n\x05value\x18\x03 \x02(\t\x12=\n\x11\x63onstraint_groups\x18\x04 \x03(\x0b\x32\".openscenairo.ValueConstraintGroup\"\x17\n\x15ParameterModifyAction\"\x14\n\x12ParameterSetAction*\xee\x01\n\rParameterType\x12\x19\n\x15PARAMETERTYPE_BOOLEAN\x10\x00\x12\x1a\n\x16PARAMETERTYPE_DATETIME\x10\x01\x12\x18\n\x14PARAMETERTYPE_DOUBLE\x10\x02\x12\x19\n\x15PARAMETERTYPE_INTEGER\x10\x03\x12\x18\n\x14PARAMETERTYPE_STRING\x10\x04\x12\x1e\n\x1aPARAMETERTYPE_UNSIGNED_INT\x10\x05\x12 \n\x1cPARAMETERTYPE_UNSIGNED_SHORT\x10\x06\x12\x15\n\x11PARAMETERTYPE_INT\x10\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openscenario_msgs.parameter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PARAMETERTYPE']._serialized_start=572
  _globals['_PARAMETERTYPE']._serialized_end=810
  _globals['_PARAMETERASSIGNMENT']._serialized_start=128
  _globals['_PARAMETERASSIGNMENT']._serialized_end=223
  _globals['_PARAMETERCONDITION']._serialized_start=225
  _globals['_PARAMETERCONDITION']._serialized_end=352
  _globals['_PARAMETERDECLARATION']._serialized_start=355
  _globals['_PARAMETERDECLARATION']._serialized_end=522
  _globals['_PARAMETERMODIFYACTION']._serialized_start=524
  _globals['_PARAMETERMODIFYACTION']._serialized_end=547
  _globals['_PARAMETERSETACTION']._serialized_start=549
  _globals['_PARAMETERSETACTION']._serialized_end=569
# @@protoc_insertion_point(module_scope)
