# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/parameter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openscenario_msgs import rule_pb2 as openscenario__msgs_dot_rule__pb2
from openscenario_msgs import valueconstraint_group_pb2 as openscenario__msgs_dot_valueconstraint__group__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!openscenario_msgs/parameter.proto\x12\x0copenscenario\x1a\x1copenscenario_msgs/rule.proto\x1a-openscenario_msgs/valueconstraint_group.proto\"_\n\x13ParameterAssignment\x12\x39\n\rparameter_ref\x18\x01 \x02(\x0b\x32\".openscenario.ParameterDeclaration\x12\r\n\x05value\x18\x02 \x02(\t\"\x7f\n\x12ParameterCondition\x12\x38\n\x0cparameterRef\x18\x01 \x02(\x0b\x32\".openscenario.ParameterDeclaration\x12 \n\x04rule\x18\x02 \x02(\x0e\x32\x12.openscenario.Rule\x12\r\n\x05value\x18\x03 \x02(\t\"\xa5\x01\n\x14ParameterDeclaration\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x32\n\rparameterType\x18\x02 \x02(\x0e\x32\x1b.openscenario.ParameterType\x12\r\n\x05value\x18\x03 \x02(\t\x12<\n\x10\x63onstraintGroups\x18\x04 \x03(\x0b\x32\".openscenario.ValueConstraintGroup\"Z\n\x15ParameterDeclarations\x12\x41\n\x15parameterDeclarations\x18\x01 \x03(\x0b\x32\".openscenario.ParameterDeclaration\"\x17\n\x15ParameterModifyAction\"\x14\n\x12ParameterSetAction*\xee\x01\n\rParameterType\x12\x19\n\x15PARAMETERTYPE_BOOLEAN\x10\x00\x12\x1a\n\x16PARAMETERTYPE_DATETIME\x10\x01\x12\x18\n\x14PARAMETERTYPE_DOUBLE\x10\x02\x12\x19\n\x15PARAMETERTYPE_INTEGER\x10\x03\x12\x18\n\x14PARAMETERTYPE_STRING\x10\x04\x12\x1e\n\x1aPARAMETERTYPE_UNSIGNED_INT\x10\x05\x12 \n\x1cPARAMETERTYPE_UNSIGNED_SHORT\x10\x06\x12\x15\n\x11PARAMETERTYPE_INT\x10\x07')

_PARAMETERTYPE = DESCRIPTOR.enum_types_by_name['ParameterType']
ParameterType = enum_type_wrapper.EnumTypeWrapper(_PARAMETERTYPE)
PARAMETERTYPE_BOOLEAN = 0
PARAMETERTYPE_DATETIME = 1
PARAMETERTYPE_DOUBLE = 2
PARAMETERTYPE_INTEGER = 3
PARAMETERTYPE_STRING = 4
PARAMETERTYPE_UNSIGNED_INT = 5
PARAMETERTYPE_UNSIGNED_SHORT = 6
PARAMETERTYPE_INT = 7


_PARAMETERASSIGNMENT = DESCRIPTOR.message_types_by_name['ParameterAssignment']
_PARAMETERCONDITION = DESCRIPTOR.message_types_by_name['ParameterCondition']
_PARAMETERDECLARATION = DESCRIPTOR.message_types_by_name['ParameterDeclaration']
_PARAMETERDECLARATIONS = DESCRIPTOR.message_types_by_name['ParameterDeclarations']
_PARAMETERMODIFYACTION = DESCRIPTOR.message_types_by_name['ParameterModifyAction']
_PARAMETERSETACTION = DESCRIPTOR.message_types_by_name['ParameterSetAction']
ParameterAssignment = _reflection.GeneratedProtocolMessageType('ParameterAssignment', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERASSIGNMENT,
  '__module__' : 'openscenario_msgs.parameter_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.ParameterAssignment)
  })
_sym_db.RegisterMessage(ParameterAssignment)

ParameterCondition = _reflection.GeneratedProtocolMessageType('ParameterCondition', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERCONDITION,
  '__module__' : 'openscenario_msgs.parameter_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.ParameterCondition)
  })
_sym_db.RegisterMessage(ParameterCondition)

ParameterDeclaration = _reflection.GeneratedProtocolMessageType('ParameterDeclaration', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERDECLARATION,
  '__module__' : 'openscenario_msgs.parameter_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.ParameterDeclaration)
  })
_sym_db.RegisterMessage(ParameterDeclaration)

ParameterDeclarations = _reflection.GeneratedProtocolMessageType('ParameterDeclarations', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERDECLARATIONS,
  '__module__' : 'openscenario_msgs.parameter_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.ParameterDeclarations)
  })
_sym_db.RegisterMessage(ParameterDeclarations)

ParameterModifyAction = _reflection.GeneratedProtocolMessageType('ParameterModifyAction', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERMODIFYACTION,
  '__module__' : 'openscenario_msgs.parameter_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.ParameterModifyAction)
  })
_sym_db.RegisterMessage(ParameterModifyAction)

ParameterSetAction = _reflection.GeneratedProtocolMessageType('ParameterSetAction', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERSETACTION,
  '__module__' : 'openscenario_msgs.parameter_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.ParameterSetAction)
  })
_sym_db.RegisterMessage(ParameterSetAction)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARAMETERTYPE._serialized_start=662
  _PARAMETERTYPE._serialized_end=900
  _PARAMETERASSIGNMENT._serialized_start=128
  _PARAMETERASSIGNMENT._serialized_end=223
  _PARAMETERCONDITION._serialized_start=225
  _PARAMETERCONDITION._serialized_end=352
  _PARAMETERDECLARATION._serialized_start=355
  _PARAMETERDECLARATION._serialized_end=520
  _PARAMETERDECLARATIONS._serialized_start=522
  _PARAMETERDECLARATIONS._serialized_end=612
  _PARAMETERMODIFYACTION._serialized_start=614
  _PARAMETERMODIFYACTION._serialized_end=637
  _PARAMETERSETACTION._serialized_start=639
  _PARAMETERSETACTION._serialized_end=659
# @@protoc_insertion_point(module_scope)
