# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/pedestrian.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openscenario_msgs import boundingbox_pb2 as openscenario__msgs_dot_boundingbox__pb2
from openscenario_msgs import parameter_pb2 as openscenario__msgs_dot_parameter__pb2
from openscenario_msgs import property_pb2 as openscenario__msgs_dot_property__pb2
from openscenario_msgs import role_pb2 as openscenario__msgs_dot_role__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"openscenario_msgs/pedestrian.proto\x12\x0copenscenario\x1a#openscenario_msgs/boundingbox.proto\x1a!openscenario_msgs/parameter.proto\x1a openscenario_msgs/property.proto\x1a\x1copenscenario_msgs/role.proto\"\xba\x02\n\nPedestrian\x12\x0c\n\x04mass\x18\x01 \x02(\x01\x12\x0f\n\x07model3d\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x02(\t\x12<\n\x12pedestrianCategory\x18\x04 \x02(\x0e\x32 .openscenario.PedestrianCategory\x12 \n\x04role\x18\x05 \x01(\x0e\x32\x12.openscenario.Role\x12\x41\n\x15parameterDeclarations\x18\x06 \x03(\x0b\x32\".openscenario.ParameterDeclaration\x12.\n\x0b\x62oundingBox\x18\x07 \x02(\x0b\x32\x19.openscenario.BoundingBox\x12,\n\nproperties\x18\x08 \x02(\x0b\x32\x18.openscenario.Properties*y\n\x12PedestrianCategory\x12\x1d\n\x19PEDESTRIANCATEGORY_ANIMAL\x10\x00\x12!\n\x1dPEDESTRIANCATEGORY_PEDESTRIAN\x10\x01\x12!\n\x1dPEDESTRIANCATEGORY_WHEELCHAIR\x10\x02')

_PEDESTRIANCATEGORY = DESCRIPTOR.enum_types_by_name['PedestrianCategory']
PedestrianCategory = enum_type_wrapper.EnumTypeWrapper(_PEDESTRIANCATEGORY)
PEDESTRIANCATEGORY_ANIMAL = 0
PEDESTRIANCATEGORY_PEDESTRIAN = 1
PEDESTRIANCATEGORY_WHEELCHAIR = 2


_PEDESTRIAN = DESCRIPTOR.message_types_by_name['Pedestrian']
Pedestrian = _reflection.GeneratedProtocolMessageType('Pedestrian', (_message.Message,), {
  'DESCRIPTOR' : _PEDESTRIAN,
  '__module__' : 'openscenario_msgs.pedestrian_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.Pedestrian)
  })
_sym_db.RegisterMessage(Pedestrian)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PEDESTRIANCATEGORY._serialized_start=505
  _PEDESTRIANCATEGORY._serialized_end=626
  _PEDESTRIAN._serialized_start=189
  _PEDESTRIAN._serialized_end=503
# @@protoc_insertion_point(module_scope)
