# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/position.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openscenario_msgs import orientation_pb2 as openscenario__msgs_dot_orientation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n openscenario_msgs/position.proto\x12\x0copenscenario\x1a#openscenario_msgs/orientation.proto\"\xd2\x04\n\x08Position\x12\x32\n\rworldPosition\x18\x01 \x01(\x0b\x32\x1b.openscenario.WorldPosition\x12\x42\n\x15relativeWorldPosition\x18\x02 \x01(\x0b\x32#.openscenario.RelativeWorldPosition\x12\x44\n\x16relativeObjectPosition\x18\x03 \x01(\x0b\x32$.openscenario.RelativeObjectPosition\x12\x30\n\x0croadPosition\x18\x04 \x01(\x0b\x32\x1a.openscenario.RoadPosition\x12@\n\x14relativeRoadPosition\x18\x05 \x01(\x0b\x32\".openscenario.RelativeRoadPosition\x12\x30\n\x0clanePosition\x18\x06 \x01(\x0b\x32\x1a.openscenario.LanePosition\x12@\n\x14relativeLanePosition\x18\x07 \x01(\x0b\x32\".openscenario.RelativeLanePosition\x12\x32\n\rroutePosition\x18\x08 \x01(\x0b\x32\x1b.openscenario.RoutePosition\x12.\n\x0bgeoPosition\x18\t \x01(\x0b\x32\x19.openscenario.GeoPosition\x12<\n\x12trajectoryPosition\x18\n \x01(\x0b\x32 .openscenario.TrajectoryPosition\"Q\n\rWorldPosition\x12\t\n\x01h\x18\x01 \x01(\x01\x12\t\n\x01p\x18\x02 \x01(\x01\x12\t\n\x01r\x18\x03 \x01(\x01\x12\t\n\x01x\x18\x04 \x02(\x01\x12\t\n\x01y\x18\x05 \x02(\x01\x12\t\n\x01z\x18\x06 \x01(\x01\"y\n\x0cLanePosition\x12\x0e\n\x06laneId\x18\x01 \x02(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x01\x12\x0e\n\x06roadId\x18\x03 \x02(\t\x12\t\n\x01s\x18\x04 \x02(\x01\x12.\n\x0borientation\x18\x05 \x01(\x0b\x32\x19.openscenario.Orientation\"\x17\n\x15RelativeWorldPosition\"\r\n\x0bGeoPosition\"\x18\n\x16RelativeObjectPosition\"\x16\n\x14RelativeLanePosition\"\x0f\n\rRoutePosition\"\x0e\n\x0cRoadPosition\"\x16\n\x14RelativeRoadPosition\"\x14\n\x12TrajectoryPosition')



_POSITION = DESCRIPTOR.message_types_by_name['Position']
_WORLDPOSITION = DESCRIPTOR.message_types_by_name['WorldPosition']
_LANEPOSITION = DESCRIPTOR.message_types_by_name['LanePosition']
_RELATIVEWORLDPOSITION = DESCRIPTOR.message_types_by_name['RelativeWorldPosition']
_GEOPOSITION = DESCRIPTOR.message_types_by_name['GeoPosition']
_RELATIVEOBJECTPOSITION = DESCRIPTOR.message_types_by_name['RelativeObjectPosition']
_RELATIVELANEPOSITION = DESCRIPTOR.message_types_by_name['RelativeLanePosition']
_ROUTEPOSITION = DESCRIPTOR.message_types_by_name['RoutePosition']
_ROADPOSITION = DESCRIPTOR.message_types_by_name['RoadPosition']
_RELATIVEROADPOSITION = DESCRIPTOR.message_types_by_name['RelativeRoadPosition']
_TRAJECTORYPOSITION = DESCRIPTOR.message_types_by_name['TrajectoryPosition']
Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'openscenario_msgs.position_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.Position)
  })
_sym_db.RegisterMessage(Position)

WorldPosition = _reflection.GeneratedProtocolMessageType('WorldPosition', (_message.Message,), {
  'DESCRIPTOR' : _WORLDPOSITION,
  '__module__' : 'openscenario_msgs.position_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.WorldPosition)
  })
_sym_db.RegisterMessage(WorldPosition)

LanePosition = _reflection.GeneratedProtocolMessageType('LanePosition', (_message.Message,), {
  'DESCRIPTOR' : _LANEPOSITION,
  '__module__' : 'openscenario_msgs.position_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.LanePosition)
  })
_sym_db.RegisterMessage(LanePosition)

RelativeWorldPosition = _reflection.GeneratedProtocolMessageType('RelativeWorldPosition', (_message.Message,), {
  'DESCRIPTOR' : _RELATIVEWORLDPOSITION,
  '__module__' : 'openscenario_msgs.position_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.RelativeWorldPosition)
  })
_sym_db.RegisterMessage(RelativeWorldPosition)

GeoPosition = _reflection.GeneratedProtocolMessageType('GeoPosition', (_message.Message,), {
  'DESCRIPTOR' : _GEOPOSITION,
  '__module__' : 'openscenario_msgs.position_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.GeoPosition)
  })
_sym_db.RegisterMessage(GeoPosition)

RelativeObjectPosition = _reflection.GeneratedProtocolMessageType('RelativeObjectPosition', (_message.Message,), {
  'DESCRIPTOR' : _RELATIVEOBJECTPOSITION,
  '__module__' : 'openscenario_msgs.position_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.RelativeObjectPosition)
  })
_sym_db.RegisterMessage(RelativeObjectPosition)

RelativeLanePosition = _reflection.GeneratedProtocolMessageType('RelativeLanePosition', (_message.Message,), {
  'DESCRIPTOR' : _RELATIVELANEPOSITION,
  '__module__' : 'openscenario_msgs.position_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.RelativeLanePosition)
  })
_sym_db.RegisterMessage(RelativeLanePosition)

RoutePosition = _reflection.GeneratedProtocolMessageType('RoutePosition', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEPOSITION,
  '__module__' : 'openscenario_msgs.position_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.RoutePosition)
  })
_sym_db.RegisterMessage(RoutePosition)

RoadPosition = _reflection.GeneratedProtocolMessageType('RoadPosition', (_message.Message,), {
  'DESCRIPTOR' : _ROADPOSITION,
  '__module__' : 'openscenario_msgs.position_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.RoadPosition)
  })
_sym_db.RegisterMessage(RoadPosition)

RelativeRoadPosition = _reflection.GeneratedProtocolMessageType('RelativeRoadPosition', (_message.Message,), {
  'DESCRIPTOR' : _RELATIVEROADPOSITION,
  '__module__' : 'openscenario_msgs.position_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.RelativeRoadPosition)
  })
_sym_db.RegisterMessage(RelativeRoadPosition)

TrajectoryPosition = _reflection.GeneratedProtocolMessageType('TrajectoryPosition', (_message.Message,), {
  'DESCRIPTOR' : _TRAJECTORYPOSITION,
  '__module__' : 'openscenario_msgs.position_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.TrajectoryPosition)
  })
_sym_db.RegisterMessage(TrajectoryPosition)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSITION._serialized_start=88
  _POSITION._serialized_end=682
  _WORLDPOSITION._serialized_start=684
  _WORLDPOSITION._serialized_end=765
  _LANEPOSITION._serialized_start=767
  _LANEPOSITION._serialized_end=888
  _RELATIVEWORLDPOSITION._serialized_start=890
  _RELATIVEWORLDPOSITION._serialized_end=913
  _GEOPOSITION._serialized_start=915
  _GEOPOSITION._serialized_end=928
  _RELATIVEOBJECTPOSITION._serialized_start=930
  _RELATIVEOBJECTPOSITION._serialized_end=954
  _RELATIVELANEPOSITION._serialized_start=956
  _RELATIVELANEPOSITION._serialized_end=978
  _ROUTEPOSITION._serialized_start=980
  _ROUTEPOSITION._serialized_end=995
  _ROADPOSITION._serialized_start=997
  _ROADPOSITION._serialized_end=1011
  _RELATIVEROADPOSITION._serialized_start=1013
  _RELATIVEROADPOSITION._serialized_end=1035
  _TRAJECTORYPOSITION._serialized_start=1037
  _TRAJECTORYPOSITION._serialized_end=1057
# @@protoc_insertion_point(module_scope)
