# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/property.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n openscenario_msgs/property.proto\x12\x0copenscenairo\"g\n\nProperties\x12%\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x16.openscenairo.Property\x12\x32\n\rcustomContent\x18\x02 \x03(\x0b\x32\x1b.openscenairo.CustomContent\"\'\n\x08Property\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\" \n\rCustomContent\x12\x0f\n\x07\x63ontent\x18\x01 \x02(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openscenario_msgs.property_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PROPERTIES']._serialized_start=50
  _globals['_PROPERTIES']._serialized_end=153
  _globals['_PROPERTY']._serialized_start=155
  _globals['_PROPERTY']._serialized_end=194
  _globals['_CUSTOMCONTENT']._serialized_start=196
  _globals['_CUSTOMCONTENT']._serialized_end=228
# @@protoc_insertion_point(module_scope)
