# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/property.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openscenario_msgs import file_pb2 as openscenario__msgs_dot_file__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n openscenario_msgs/property.proto\x12\x0copenscenario\x1a\x1copenscenario_msgs/file.proto\"[\n\nProperties\x12*\n\nproperties\x18\x01 \x03(\x0b\x32\x16.openscenario.Property\x12!\n\x05\x66iles\x18\x02 \x03(\x0b\x32\x12.openscenario.File\"\'\n\x08Property\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\" \n\rCustomContent\x12\x0f\n\x07\x63ontent\x18\x01 \x02(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openscenario_msgs.property_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROPERTIES._serialized_start=80
  _PROPERTIES._serialized_end=171
  _PROPERTY._serialized_start=173
  _PROPERTY._serialized_end=212
  _CUSTOMCONTENT._serialized_start=214
  _CUSTOMCONTENT._serialized_end=246
# @@protoc_insertion_point(module_scope)
