[tool.poetry]
name = "openscenario_msgs"
version = "0.2.0"
description = ""
authors = ["Changnam"]
readme = "README.md"
packages = [
    { include = "*.py" }
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
