# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/role.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1copenscenario_msgs/role.proto\x12\x0copenscenario*y\n\x04Role\x12\x08\n\x04NONE\x10\x00\x12\r\n\tAMBULANCE\x10\x01\x12\t\n\x05\x43IVIL\x10\x02\x12\x08\n\x04\x46IRE\x10\x03\x12\x0c\n\x08MILITARY\x10\x04\x12\n\n\x06POLICE\x10\x05\x12\x14\n\x10PUBLIC_TRANSPORT\x10\x06\x12\x13\n\x0fROAD_ASSISTANCE\x10\x07')

_ROLE = DESCRIPTOR.enum_types_by_name['Role']
Role = enum_type_wrapper.EnumTypeWrapper(_ROLE)
NONE = 0
AMBULANCE = 1
CIVIL = 2
FIRE = 3
MILITARY = 4
POLICE = 5
PUBLIC_TRANSPORT = 6
ROAD_ASSISTANCE = 7


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROLE._serialized_start=46
  _ROLE._serialized_end=167
# @@protoc_insertion_point(module_scope)
