# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/role.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1copenscenario_msgs/role.proto\x12\x0copenscenairo*y\n\x04Role\x12\x08\n\x04NONE\x10\x00\x12\r\n\tAMBULANCE\x10\x01\x12\t\n\x05\x43IVIL\x10\x02\x12\x08\n\x04\x46IRE\x10\x03\x12\x0c\n\x08MILITARY\x10\x04\x12\n\n\x06POLICE\x10\x05\x12\x14\n\x10PUBLIC_TRANSPORT\x10\x06\x12\x13\n\x0fROAD_ASSISTANCE\x10\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openscenario_msgs.role_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ROLE']._serialized_start=46
  _globals['_ROLE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
