# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/rule.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1copenscenario_msgs/rule.proto\x12\x0copenscenario*p\n\x04Rule\x12\x0c\n\x08\x45QUAL_TO\x10\x00\x12\x10\n\x0cGREATER_THAN\x10\x01\x12\r\n\tLESS_THAN\x10\x02\x12\x14\n\x10GREATER_OR_EQUAL\x10\x03\x12\x11\n\rLESS_OR_EQUAL\x10\x04\x12\x10\n\x0cNOT_EQUAL_TO\x10\x05')

_RULE = DESCRIPTOR.enum_types_by_name['Rule']
Rule = enum_type_wrapper.EnumTypeWrapper(_RULE)
EQUAL_TO = 0
GREATER_THAN = 1
LESS_THAN = 2
GREATER_OR_EQUAL = 3
LESS_OR_EQUAL = 4
NOT_EQUAL_TO = 5


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RULE._serialized_start=46
  _RULE._serialized_end=158
# @@protoc_insertion_point(module_scope)
