# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/shape.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openscenario_msgs import position_pb2 as openscenario__msgs_dot_position__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dopenscenario_msgs/shape.proto\x12\x0copenscenairo\x1a openscenario_msgs/position.proto\"\x7f\n\x05Shape\x12(\n\x08polyline\x18\x01 \x01(\x0b\x32\x16.openscenairo.Polyline\x12(\n\x08\x63lothoid\x18\x02 \x01(\x0b\x32\x16.openscenairo.Clothoid\x12\"\n\x05nurbs\x18\x03 \x01(\x0b\x32\x13.openscenairo.Nurbs\"2\n\x08Polyline\x12&\n\x08vertices\x18\x01 \x03(\x0b\x32\x14.openscenairo.Vertex\"@\n\x06Vertex\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12(\n\x08position\x18\x02 \x02(\x0b\x32\x16.openscenairo.Position\"\n\n\x08\x43lothoid\"\x07\n\x05Nurbs\"V\n\x0c\x43ontrolPoint\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x0e\n\x06weight\x18\x02 \x01(\x01\x12(\n\x08position\x18\x03 \x02(\x0b\x32\x16.openscenairo.Position')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openscenario_msgs.shape_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SHAPE']._serialized_start=81
  _globals['_SHAPE']._serialized_end=208
  _globals['_POLYLINE']._serialized_start=210
  _globals['_POLYLINE']._serialized_end=260
  _globals['_VERTEX']._serialized_start=262
  _globals['_VERTEX']._serialized_end=326
  _globals['_CLOTHOID']._serialized_start=328
  _globals['_CLOTHOID']._serialized_end=338
  _globals['_NURBS']._serialized_start=340
  _globals['_NURBS']._serialized_end=347
  _globals['_CONTROLPOINT']._serialized_start=349
  _globals['_CONTROLPOINT']._serialized_end=435
# @@protoc_insertion_point(module_scope)
