# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/time_of_day.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#openscenario_msgs/time_of_day.proto\x12\x0copenscenario\"0\n\tTimeOfDay\x12\x11\n\tanimation\x18\x01 \x02(\x08\x12\x10\n\x08\x64\x61teTime\x18\x02 \x02(\x01')



_TIMEOFDAY = DESCRIPTOR.message_types_by_name['TimeOfDay']
TimeOfDay = _reflection.GeneratedProtocolMessageType('TimeOfDay', (_message.Message,), {
  'DESCRIPTOR' : _TIMEOFDAY,
  '__module__' : 'openscenario_msgs.time_of_day_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.TimeOfDay)
  })
_sym_db.RegisterMessage(TimeOfDay)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMEOFDAY._serialized_start=53
  _TIMEOFDAY._serialized_end=101
# @@protoc_insertion_point(module_scope)
