# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/time_of_day.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#openscenario_msgs/time_of_day.proto\x12\x0copenscenairo\"0\n\tTimeOfDay\x12\x11\n\tanimation\x18\x01 \x02(\x08\x12\x10\n\x08\x64\x61teTime\x18\x02 \x02(\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openscenario_msgs.time_of_day_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TIMEOFDAY']._serialized_start=53
  _globals['_TIMEOFDAY']._serialized_end=101
# @@protoc_insertion_point(module_scope)
