# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/traffic_signal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&openscenario_msgs/traffic_signal.proto\x12\x0copenscenario\"\xb3\x01\n\x13TrafficSignalAction\x12R\n\x1dtrafficSignalControllerAction\x18\x01 \x01(\x0b\x32+.openscenario.TrafficSignalControllerAction\x12H\n\x18trafficSignalStateAction\x18\x02 \x01(\x0b\x32&.openscenario.TrafficSignalStateAction\"\xa0\x01\n\x1dTrafficSignalControllerAction\x12\r\n\x05phase\x18\x01 \x02(\t\x12I\n\x1atrafficSignalControllerRef\x18\x02 \x02(\x0b\x32%.openscenario.TrafficSignalController\x12%\n\x08phaseRef\x18\x03 \x02(\x0b\x32\x13.openscenario.Phase\"7\n\x18TrafficSignalStateAction\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05state\x18\x02 \x02(\t\"(\n\x17TrafficSignalGroupState\x12\r\n\x05state\x18\x01 \x02(\t\"<\n\x12TrafficSignalState\x12\r\n\x05state\x18\x01 \x02(\t\x12\x17\n\x0ftrafficSignalId\x18\x02 \x02(\t\"\xa3\x01\n TrafficSignalControllerCondition\x12\r\n\x05phase\x18\x01 \x02(\t\x12I\n\x1atrafficSignalControllerRef\x18\x02 \x02(\x0b\x32%.openscenario.TrafficSignalController\x12%\n\x08phaseRef\x18\x03 \x03(\x0b\x32\x13.openscenario.Phase\"Y\n\x0eTrafficSignals\x12G\n\x18trafficSignalControllers\x18\x01 \x03(\x0b\x32%.openscenario.TrafficSignalController\"n\n\x17TrafficSignalController\x12\r\n\x05\x64\x65lay\x18\x01 \x01(\x01\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x11\n\treference\x18\x03 \x01(\t\x12#\n\x06phases\x18\x04 \x03(\x0b\x32\x13.openscenario.Phase\"5\n\x16TrafficSignalCondition\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05state\x18\x02 \x02(\t\"\xaf\x01\n\x05Phase\x12\x10\n\x08\x64uration\x18\x01 \x02(\x01\x12\x0c\n\x04name\x18\x02 \x02(\t\x12=\n\x13trafficSignalStates\x18\x03 \x03(\x0b\x32 .openscenario.TrafficSignalState\x12G\n\x18trafficeSignalGroupState\x18\x04 \x01(\x0b\x32%.openscenario.TrafficSignalGroupState')



_TRAFFICSIGNALACTION = DESCRIPTOR.message_types_by_name['TrafficSignalAction']
_TRAFFICSIGNALCONTROLLERACTION = DESCRIPTOR.message_types_by_name['TrafficSignalControllerAction']
_TRAFFICSIGNALSTATEACTION = DESCRIPTOR.message_types_by_name['TrafficSignalStateAction']
_TRAFFICSIGNALGROUPSTATE = DESCRIPTOR.message_types_by_name['TrafficSignalGroupState']
_TRAFFICSIGNALSTATE = DESCRIPTOR.message_types_by_name['TrafficSignalState']
_TRAFFICSIGNALCONTROLLERCONDITION = DESCRIPTOR.message_types_by_name['TrafficSignalControllerCondition']
_TRAFFICSIGNALS = DESCRIPTOR.message_types_by_name['TrafficSignals']
_TRAFFICSIGNALCONTROLLER = DESCRIPTOR.message_types_by_name['TrafficSignalController']
_TRAFFICSIGNALCONDITION = DESCRIPTOR.message_types_by_name['TrafficSignalCondition']
_PHASE = DESCRIPTOR.message_types_by_name['Phase']
TrafficSignalAction = _reflection.GeneratedProtocolMessageType('TrafficSignalAction', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICSIGNALACTION,
  '__module__' : 'openscenario_msgs.traffic_signal_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.TrafficSignalAction)
  })
_sym_db.RegisterMessage(TrafficSignalAction)

TrafficSignalControllerAction = _reflection.GeneratedProtocolMessageType('TrafficSignalControllerAction', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICSIGNALCONTROLLERACTION,
  '__module__' : 'openscenario_msgs.traffic_signal_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.TrafficSignalControllerAction)
  })
_sym_db.RegisterMessage(TrafficSignalControllerAction)

TrafficSignalStateAction = _reflection.GeneratedProtocolMessageType('TrafficSignalStateAction', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICSIGNALSTATEACTION,
  '__module__' : 'openscenario_msgs.traffic_signal_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.TrafficSignalStateAction)
  })
_sym_db.RegisterMessage(TrafficSignalStateAction)

TrafficSignalGroupState = _reflection.GeneratedProtocolMessageType('TrafficSignalGroupState', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICSIGNALGROUPSTATE,
  '__module__' : 'openscenario_msgs.traffic_signal_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.TrafficSignalGroupState)
  })
_sym_db.RegisterMessage(TrafficSignalGroupState)

TrafficSignalState = _reflection.GeneratedProtocolMessageType('TrafficSignalState', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICSIGNALSTATE,
  '__module__' : 'openscenario_msgs.traffic_signal_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.TrafficSignalState)
  })
_sym_db.RegisterMessage(TrafficSignalState)

TrafficSignalControllerCondition = _reflection.GeneratedProtocolMessageType('TrafficSignalControllerCondition', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICSIGNALCONTROLLERCONDITION,
  '__module__' : 'openscenario_msgs.traffic_signal_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.TrafficSignalControllerCondition)
  })
_sym_db.RegisterMessage(TrafficSignalControllerCondition)

TrafficSignals = _reflection.GeneratedProtocolMessageType('TrafficSignals', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICSIGNALS,
  '__module__' : 'openscenario_msgs.traffic_signal_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.TrafficSignals)
  })
_sym_db.RegisterMessage(TrafficSignals)

TrafficSignalController = _reflection.GeneratedProtocolMessageType('TrafficSignalController', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICSIGNALCONTROLLER,
  '__module__' : 'openscenario_msgs.traffic_signal_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.TrafficSignalController)
  })
_sym_db.RegisterMessage(TrafficSignalController)

TrafficSignalCondition = _reflection.GeneratedProtocolMessageType('TrafficSignalCondition', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICSIGNALCONDITION,
  '__module__' : 'openscenario_msgs.traffic_signal_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.TrafficSignalCondition)
  })
_sym_db.RegisterMessage(TrafficSignalCondition)

Phase = _reflection.GeneratedProtocolMessageType('Phase', (_message.Message,), {
  'DESCRIPTOR' : _PHASE,
  '__module__' : 'openscenario_msgs.traffic_signal_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.Phase)
  })
_sym_db.RegisterMessage(Phase)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAFFICSIGNALACTION._serialized_start=57
  _TRAFFICSIGNALACTION._serialized_end=236
  _TRAFFICSIGNALCONTROLLERACTION._serialized_start=239
  _TRAFFICSIGNALCONTROLLERACTION._serialized_end=399
  _TRAFFICSIGNALSTATEACTION._serialized_start=401
  _TRAFFICSIGNALSTATEACTION._serialized_end=456
  _TRAFFICSIGNALGROUPSTATE._serialized_start=458
  _TRAFFICSIGNALGROUPSTATE._serialized_end=498
  _TRAFFICSIGNALSTATE._serialized_start=500
  _TRAFFICSIGNALSTATE._serialized_end=560
  _TRAFFICSIGNALCONTROLLERCONDITION._serialized_start=563
  _TRAFFICSIGNALCONTROLLERCONDITION._serialized_end=726
  _TRAFFICSIGNALS._serialized_start=728
  _TRAFFICSIGNALS._serialized_end=817
  _TRAFFICSIGNALCONTROLLER._serialized_start=819
  _TRAFFICSIGNALCONTROLLER._serialized_end=929
  _TRAFFICSIGNALCONDITION._serialized_start=931
  _TRAFFICSIGNALCONDITION._serialized_end=984
  _PHASE._serialized_start=987
  _PHASE._serialized_end=1162
# @@protoc_insertion_point(module_scope)
