# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/traffic_signal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&openscenario_msgs/traffic_signal.proto\x12\x0copenscenairo\"\xb3\x01\n\x13TrafficSignalAction\x12R\n\x1dtrafficSignalControllerAction\x18\x01 \x01(\x0b\x32+.openscenairo.TrafficSignalControllerAction\x12H\n\x18trafficSignalStateAction\x18\x02 \x01(\x0b\x32&.openscenairo.TrafficSignalStateAction\"\xa0\x01\n\x1dTrafficSignalControllerAction\x12\r\n\x05phase\x18\x01 \x02(\t\x12I\n\x1atrafficSignalControllerRef\x18\x02 \x02(\x0b\x32%.openscenairo.TrafficSignalController\x12%\n\x08phaseRef\x18\x03 \x02(\x0b\x32\x13.openscenairo.Phase\"7\n\x18TrafficSignalStateAction\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05state\x18\x02 \x02(\t\"(\n\x17TrafficSignalGroupState\x12\r\n\x05state\x18\x01 \x02(\t\"<\n\x12TrafficSignalState\x12\r\n\x05state\x18\x01 \x02(\t\x12\x17\n\x0ftrafficSignalId\x18\x02 \x02(\t\"\xa3\x01\n TrafficSignalControllerCondition\x12\r\n\x05phase\x18\x01 \x02(\t\x12I\n\x1atrafficSignalControllerRef\x18\x02 \x02(\x0b\x32%.openscenairo.TrafficSignalController\x12%\n\x08phaseRef\x18\x03 \x03(\x0b\x32\x13.openscenairo.Phase\"n\n\x17TrafficSignalController\x12\r\n\x05\x64\x65lay\x18\x01 \x01(\x01\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x11\n\treference\x18\x03 \x01(\t\x12#\n\x06phases\x18\x04 \x03(\x0b\x32\x13.openscenairo.Phase\"5\n\x16TrafficSignalCondition\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05state\x18\x02 \x02(\t\"\xaf\x01\n\x05Phase\x12\x10\n\x08\x64uration\x18\x01 \x02(\x01\x12\x0c\n\x04name\x18\x02 \x02(\t\x12=\n\x13trafficSignalStates\x18\x03 \x03(\x0b\x32 .openscenairo.TrafficSignalState\x12G\n\x18trafficeSignalGroupState\x18\x04 \x01(\x0b\x32%.openscenairo.TrafficSignalGroupState')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openscenario_msgs.traffic_signal_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TRAFFICSIGNALACTION']._serialized_start=57
  _globals['_TRAFFICSIGNALACTION']._serialized_end=236
  _globals['_TRAFFICSIGNALCONTROLLERACTION']._serialized_start=239
  _globals['_TRAFFICSIGNALCONTROLLERACTION']._serialized_end=399
  _globals['_TRAFFICSIGNALSTATEACTION']._serialized_start=401
  _globals['_TRAFFICSIGNALSTATEACTION']._serialized_end=456
  _globals['_TRAFFICSIGNALGROUPSTATE']._serialized_start=458
  _globals['_TRAFFICSIGNALGROUPSTATE']._serialized_end=498
  _globals['_TRAFFICSIGNALSTATE']._serialized_start=500
  _globals['_TRAFFICSIGNALSTATE']._serialized_end=560
  _globals['_TRAFFICSIGNALCONTROLLERCONDITION']._serialized_start=563
  _globals['_TRAFFICSIGNALCONTROLLERCONDITION']._serialized_end=726
  _globals['_TRAFFICSIGNALCONTROLLER']._serialized_start=728
  _globals['_TRAFFICSIGNALCONTROLLER']._serialized_end=838
  _globals['_TRAFFICSIGNALCONDITION']._serialized_start=840
  _globals['_TRAFFICSIGNALCONDITION']._serialized_end=893
  _globals['_PHASE']._serialized_start=896
  _globals['_PHASE']._serialized_end=1071
# @@protoc_insertion_point(module_scope)
