# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/transition_dynamics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openscenario_msgs import following_mode_pb2 as openscenario__msgs_dot_following__mode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+openscenario_msgs/transition_dynamics.proto\x12\x0copenscenario\x1a&openscenario_msgs/following_mode.proto\"\xe6\x02\n\x12TransitionDynamics\x12M\n\x11\x64ynamicsDimension\x18\x01 \x02(\x0e\x32\x32.openscenario.TransitionDynamics.DynamicsDimension\x12\x45\n\rdynamicsShape\x18\x02 \x02(\x0e\x32..openscenario.TransitionDynamics.DynamicsShape\x12\x32\n\rfollowingMode\x18\x03 \x02(\x0e\x32\x1b.openscenario.FollowingMode\x12\r\n\x05value\x18\x04 \x02(\x01\"5\n\x11\x44ynamicsDimension\x12\x0c\n\x08\x44ISTANCE\x10\x00\x12\x08\n\x04RATE\x10\x01\x12\x08\n\x04TIME\x10\x02\"@\n\rDynamicsShape\x12\t\n\x05\x43UBIC\x10\x00\x12\n\n\x06LINEAR\x10\x01\x12\x0e\n\nSINUSOIDAL\x10\x02\x12\x08\n\x04STEP\x10\x03')



_TRANSITIONDYNAMICS = DESCRIPTOR.message_types_by_name['TransitionDynamics']
_TRANSITIONDYNAMICS_DYNAMICSDIMENSION = _TRANSITIONDYNAMICS.enum_types_by_name['DynamicsDimension']
_TRANSITIONDYNAMICS_DYNAMICSSHAPE = _TRANSITIONDYNAMICS.enum_types_by_name['DynamicsShape']
TransitionDynamics = _reflection.GeneratedProtocolMessageType('TransitionDynamics', (_message.Message,), {
  'DESCRIPTOR' : _TRANSITIONDYNAMICS,
  '__module__' : 'openscenario_msgs.transition_dynamics_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.TransitionDynamics)
  })
_sym_db.RegisterMessage(TransitionDynamics)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSITIONDYNAMICS._serialized_start=102
  _TRANSITIONDYNAMICS._serialized_end=460
  _TRANSITIONDYNAMICS_DYNAMICSDIMENSION._serialized_start=341
  _TRANSITIONDYNAMICS_DYNAMICSDIMENSION._serialized_end=394
  _TRANSITIONDYNAMICS_DYNAMICSSHAPE._serialized_start=396
  _TRANSITIONDYNAMICS_DYNAMICSSHAPE._serialized_end=460
# @@protoc_insertion_point(module_scope)
