# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscenario_msgs/valueconstraint_group.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openscenario_msgs import rule_pb2 as openscenario__msgs_dot_rule__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-openscenario_msgs/valueconstraint_group.proto\x12\x0copenscenario\x1a\x1copenscenario_msgs/rule.proto\"J\n\x14ValueConstraintGroup\x12\x32\n\x0b\x63onstraints\x18\x01 \x03(\x0b\x32\x1d.openscenario.ValueConstraint\"B\n\x0fValueConstraint\x12 \n\x04rule\x18\x01 \x02(\x0e\x32\x12.openscenario.Rule\x12\r\n\x05value\x18\x02 \x02(\t')



_VALUECONSTRAINTGROUP = DESCRIPTOR.message_types_by_name['ValueConstraintGroup']
_VALUECONSTRAINT = DESCRIPTOR.message_types_by_name['ValueConstraint']
ValueConstraintGroup = _reflection.GeneratedProtocolMessageType('ValueConstraintGroup', (_message.Message,), {
  'DESCRIPTOR' : _VALUECONSTRAINTGROUP,
  '__module__' : 'openscenario_msgs.valueconstraint_group_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.ValueConstraintGroup)
  })
_sym_db.RegisterMessage(ValueConstraintGroup)

ValueConstraint = _reflection.GeneratedProtocolMessageType('ValueConstraint', (_message.Message,), {
  'DESCRIPTOR' : _VALUECONSTRAINT,
  '__module__' : 'openscenario_msgs.valueconstraint_group_pb2'
  # @@protoc_insertion_point(class_scope:openscenario.ValueConstraint)
  })
_sym_db.RegisterMessage(ValueConstraint)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VALUECONSTRAINTGROUP._serialized_start=93
  _VALUECONSTRAINTGROUP._serialized_end=167
  _VALUECONSTRAINT._serialized_start=169
  _VALUECONSTRAINT._serialized_end=235
# @@protoc_insertion_point(module_scope)
