# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgs/lane_position.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18msgs/lane_position.proto\x12\x0copenscenario\"<\n\x0bOrientation\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\t\n\x01h\x18\x02 \x01(\x01\x12\t\n\x01p\x18\x03 \x01(\x01\x12\t\n\x01r\x18\x04 \x01(\x01\"y\n\x0cLanePosition\x12\x0e\n\x06roadId\x18\x01 \x01(\t\x12\x0e\n\x06laneId\x18\x02 \x01(\t\x12\t\n\x01s\x18\x03 \x01(\x01\x12\x0e\n\x06offset\x18\x04 \x01(\x01\x12.\n\x0borientation\x18\x05 \x01(\x0b\x32\x19.openscenario.Orientation')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msgs.lane_position_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ORIENTATION']._serialized_start=42
  _globals['_ORIENTATION']._serialized_end=102
  _globals['_LANEPOSITION']._serialized_start=104
  _globals['_LANEPOSITION']._serialized_end=225
# @@protoc_insertion_point(module_scope)
